final List<String> rae = [
  "neno",
  "torre",
  "xerion",
  "fran",
  "paco",
  "xulio",
  "depor",
  "djukic",
  "moore",
  "bonilla",
  "timon",
  "agrela",
  "xuxan",
  "mallos",
  "marea",
  "orzan",
  "riazor",
  "bul",
  "lugris",
  "bebeto",
  "malos",
  "opinion",
  "pita",
  "marina",
  "osg",
  "kel",
  "oistes",
  "chorba",
  "castros",
  "katanga",
  "liceo",
  "foton",
  "Gaston",
  "domus",
  "rubine",
  "chukel",
  "ines",
  "dandy",
  "moon",
  "barul",
  "playa",
  "galera",
  "cuac",
  "Tsxg",
  "Egeo",
  "Eloytp",
  "Humor",
  "Porron",
  "Repi",
  "pucho",
  "oar",
  "Inox",
  "Rus",
  "Ney",
  "paseo",
  "boedo",
  "puerto",
  "lavedra",
  "alvedro",
  "neno",
  "torre",
  "xerion",
  "fran",
  "paco",
  "xulio",
  "depor",
  "djukic",
  "moore",
  "bonilla",
  "timon",
  "agrela",
  "xuxan",
  "mallos",
  "marea",
  "orzan",
  "riazor",
  "bul",
  "lugris",
  "bebeto",
  "malos",
  "opinion",
  "pita",
  "marina",
  "osg",
  "kel",
  "oistes",
  "chorba",
  "castros",
  "katanga",
  "liceo",
  "foton",
  "Gaston",
  "domus",
  "rubine",
  "chukel",
  "ines",
  "dandy",
  "moon",
  "barul",
  "playa",
  "galera",
  "cuac",
  "Tsxg",
  "Egeo",
  "Eloytp",
  "Humor",
  "Porron",
  "Repi",
  "pucho",
  "oar",
  "Inox",
  "Rus",
  "Ney",
  "paseo",
  "boedo",
  "puerto",
  "lavedra",
  "alvedro",
  "neno",
  "torre",
  "xerion",
  "fran",
  "paco",
  "xulio",
  "depor",
  "djukic",
  "moore",
  "bonilla",
  "timon",
  "agrela",
  "xuxan",
  "mallos",
  "marea",
  "orzan",
  "riazor",
  "bul",
  "lugris",
  "bebeto",
  "malos",
  "opinion",
  "pita",
  "marina",
  "osg",
  "kel",
  "oistes",
  "chorba",
  "castros",
  "katanga",
  "liceo",
  "foton",
  "Gaston",
  "domus",
  "rubine",
  "chukel",
  "ines",
  "dandy",
  "moon",
  "barul",
  "playa",
  "galera",
  "cuac",
  "Tsxg",
  "Egeo",
  "Eloytp",
  "Humor",
  "Porron",
  "Repi",
  "pucho",
  "oar",
  "Inox",
  "Rus",
  "Ney",
  "paseo",
  "boedo",
  "puerto",
  "lavedra",
  "alvedro",
  "neno",
  "torre",
  "xerion",
  "fran",
  "paco",
  "xulio",
  "depor",
  "djukic",
  "moore",
  "bonilla",
  "timon",
  "agrela",
  "xuxan",
  "mallos",
  "marea",
  "orzan",
  "riazor",
  "bul",
  "lugris",
  "bebeto",
  "malos",
  "opinion",
  "pita",
  "marina",
  "osg",
  "kel",
  "oistes",
  "chorba",
  "castros",
  "katanga",
  "liceo",
  "foton",
  "Gaston",
  "domus",
  "rubine",
  "chukel",
  "ines",
  "dandy",
  "moon",
  "barul",
  "playa",
  "galera",
  "cuac",
  "Tsxg",
  "Egeo",
  "Eloytp",
  "Humor",
  "Porron",
  "Repi",
  "pucho",
  "oar",
  "Inox",
  "Rus",
  "Ney",
  "paseo",
  "boedo",
  "puerto",
  "lavedra",
  "alvedro",
  "neno",
  "torre",
  "xerion",
  "fran",
  "paco",
  "xulio",
  "depor",
  "djukic",
  "moore",
  "bonilla",
  "timon",
  "agrela",
  "xuxan",
  "mallos",
  "marea",
  "orzan",
  "riazor",
  "bul",
  "lugris",
  "bebeto",
  "malos",
  "opinion",
  "pita",
  "marina",
  "osg",
  "kel",
  "oistes",
  "chorba",
  "castros",
  "katanga",
  "liceo",
  "foton",
  "Gaston",
  "domus",
  "rubine",
  "chukel",
  "ines",
  "dandy",
  "moon",
  "barul",
  "playa",
  "galera",
  "cuac",
  "Tsxg",
  "Egeo",
  "Eloytp",
  "Humor",
  "Porron",
  "Repi",
  "pucho",
  "oar",
  "Inox",
  "Rus",
  "Ney",
  "paseo",
  "boedo",
  "puerto",
  "lavedra",
  "alvedro",
  "neno",
  "torre",
  "xerion",
  "fran",
  "paco",
  "xulio",
  "depor",
  "djukic",
  "moore",
  "bonilla",
  "timon",
  "agrela",
  "xuxan",
  "mallos",
  "marea",
  "orzan",
  "riazor",
  "bul",
  "lugris",
  "bebeto",
  "malos",
  "opinion",
  "pita",
  "marina",
  "osg",
  "kel",
  "oistes",
  "chorba",
  "castros",
  "katanga",
  "liceo",
  "foton",
  "Gaston",
  "domus",
  "rubine",
  "chukel",
  "ines",
  "dandy",
  "moon",
  "barul",
  "playa",
  "galera",
  "cuac",
  "Tsxg",
  "Egeo",
  "Eloytp",
  "Humor",
  "Porron",
  "Repi",
  "pucho",
  "oar",
  "Inox",
  "Rus",
  "Ney",
  "paseo",
  "boedo",
  "puerto",
  "lavedra",
  "alvedro",
  "neno",
  "torre",
  "xerion",
  "fran",
  "paco",
  "xulio",
  "depor",
  "djukic",
  "moore",
  "bonilla",
  "timon",
  "agrela",
  "xuxan",
  "mallos",
  "marea",
  "orzan",
  "riazor",
  "bul",
  "lugris",
  "bebeto",
  "malos",
  "opinion",
  "pita",
  "marina",
  "osg",
  "kel",
  "oistes",
  "chorba",
  "castros",
  "katanga",
  "liceo",
  "foton",
  "Gaston",
  "domus",
  "rubine",
  "chukel",
  "ines",
  "dandy",
  "moon",
  "barul",
  "playa",
  "galera",
  "cuac",
  "Tsxg",
  "Egeo",
  "Eloytp",
  "Humor",
  "Porron",
  "Repi",
  "pucho",
  "oar",
  "Inox",
  "Rus",
  "Ney",
  "paseo",
  "boedo",
  "puerto",
  "lavedra",
  "alvedro"
];

final List<String> raeXerion = [
  "Chico",
  "Patrimonio de la humanidad",
  "Está debajo de la torre",
  "O noso NENO",
  "El alcalde que más duró",
  "El alcalde que nadie esperaba",
  "El equipo que ganó la liga",
  "Falló un penalti el último partido de liga",
  "Su tumba está en los jardines de San  Carlos",
  "Los mejores churros",
  "Los segundos mejores churros",
  "Polígono donde está Estrella Galicia",
  "Un barrio en construcción",
  "Un barrio que quieren hacer peligroso",
  "El partido que nadie esperaba",
  "Antes se salía de fiesta por esa zona",
  "El estadio del DEPOR",
  "Culo en koruño",
  "Los mejores murales son suyos",
  "José Roberto Gama de Oliveira",
  "El mejor bar de la calle Galera",
  "El periódico que no miente",
  "Se llamaba María y nos salvó de los ingleses",
  "Galerías y cafés hay en esta calle",
  "La orquesta que toca en el palacio de la Ópera",
  "Casa en Koruño",
  "Me oyes...",
  "Chica en Koruño",
  "El barrio que tiene el parque de San Diego",
  "El barrio que atacaba a Corea ",
  "El hockey corre por su colegio",
  "Cuando te pegan en Koruño",
  "El caballito de mar que salvaron en el Aquarium",
  "El museo del vídeo del parto",
  "La calle con más viento de Coruña",
  "Perro en Koruño",
  "La primera alcaldesa",
  "Zapatería clásica",
  "Antes era la Green",
  "Basura en Koruño",
  "Hay muchas en la ciudad",
  "La calle de los bares de día",
  "La radio comunitaria de A Coruña",
  "El tribunal que nunca defrauda a Feijoo",
  "Bar de rock que fue todo un templo",
  "Twitero famoso",
  "Se hacía botellón pero ahora no se puede hablar en esa plaza",
  "El suelo de ese bar tiene muchos cacahuetes",
  "Era fácil acabar en una foliada en ese bar",
  "Nombre de un mito de la música",
  "Club de balonmano",
  "A último hora se iba a este sitio casi sin música",
  "Alguna vez resbalaste por sus escaleras y lo sabes",
  "Escultura mítica de un perro",
  "Es la gran obra de PACO",
  "Apellido de un mito de la música",
  "Ahora hay uno exterior",
  "La avenida que parece una autopista",
  "El aeropuerto que no debía existir",
  "Chico",
  "Patrimonio de la humanidad",
  "Está debajo de la torre",
  "O noso NENO",
  "El alcalde que más duró",
  "El alcalde que nadie esperaba",
  "El equipo que ganó la liga",
  "Falló un penalti el último partido de liga",
  "Su tumba está en los jardines de San  Carlos",
  "Los mejores churros",
  "Los segundos mejores churros",
  "Polígono donde está Estrella Galicia",
  "Un barrio en construcción",
  "Un barrio que quieren hacer peligroso",
  "El partido que nadie esperaba",
  "Antes se salía de fiesta por esa zona",
  "El estadio del DEPOR",
  "Culo en koruño",
  "Los mejores murales son suyos",
  "José Roberto Gama de Oliveira",
  "El mejor bar de la calle Galera",
  "El periódico que no miente",
  "Se llamaba María y nos salvó de los ingleses",
  "Galerías y cafés hay en esta calle",
  "La orquesta que toca en el palacio de la Ópera",
  "Casa en Koruño",
  "Me oyes...",
  "Chica en Koruño",
  "El barrio que tiene el parque de San Diego",
  "El barrio que atacaba a Corea ",
  "El hockey corre por su colegio",
  "Cuando te pegan en Koruño",
  "El caballito de mar que salvaron en el Aquarium",
  "El museo del vídeo del parto",
  "La calle con más viento de Coruña",
  "Perro en Koruño",
  "La primera alcaldesa",
  "Zapatería clásica",
  "Antes era la Green",
  "Basura en Koruño",
  "Hay muchas en la ciudad",
  "La calle de los bares de día",
  "La radio comunitaria de A Coruña",
  "El tribunal que nunca defrauda a Feijoo",
  "Bar de rock que fue todo un templo",
  "Twitero famoso",
  "Se hacía botellón pero ahora no se puede hablar en esa plaza",
  "El suelo de ese bar tiene muchos cacahuetes",
  "Era fácil acabar en una foliada en ese bar",
  "Nombre de un mito de la música",
  "Club de balonmano",
  "A último hora se iba a este sitio casi sin música",
  "Alguna vez resbalaste por sus escaleras y lo sabes",
  "Escultura mítica de un perro",
  "Es la gran obra de PACO",
  "Apellido de un mito de la música",
  "Ahora hay uno exterior",
  "La avenida que parece una autopista",
  "El aeropuerto que no debía existir",
  "Chico",
  "Patrimonio de la humanidad",
  "Está debajo de la torre",
  "O noso NENO",
  "El alcalde que más duró",
  "El alcalde que nadie esperaba",
  "El equipo que ganó la liga",
  "Falló un penalti el último partido de liga",
  "Su tumba está en los jardines de San  Carlos",
  "Los mejores churros",
  "Los segundos mejores churros",
  "Polígono donde está Estrella Galicia",
  "Un barrio en construcción",
  "Un barrio que quieren hacer peligroso",
  "El partido que nadie esperaba",
  "Antes se salía de fiesta por esa zona",
  "El estadio del DEPOR",
  "Culo en koruño",
  "Los mejores murales son suyos",
  "José Roberto Gama de Oliveira",
  "El mejor bar de la calle Galera",
  "El periódico que no miente",
  "Se llamaba María y nos salvó de los ingleses",
  "Galerías y cafés hay en esta calle",
  "La orquesta que toca en el palacio de la Ópera",
  "Casa en Koruño",
  "Me oyes...",
  "Chica en Koruño",
  "El barrio que tiene el parque de San Diego",
  "El barrio que atacaba a Corea ",
  "El hockey corre por su colegio",
  "Cuando te pegan en Koruño",
  "El caballito de mar que salvaron en el Aquarium",
  "El museo del vídeo del parto",
  "La calle con más viento de Coruña",
  "Perro en Koruño",
  "La primera alcaldesa",
  "Zapatería clásica",
  "Antes era la Green",
  "Basura en Koruño",
  "Hay muchas en la ciudad",
  "La calle de los bares de día",
  "La radio comunitaria de A Coruña",
  "El tribunal que nunca defrauda a Feijoo",
  "Bar de rock que fue todo un templo",
  "Twitero famoso",
  "Se hacía botellón pero ahora no se puede hablar en esa plaza",
  "El suelo de ese bar tiene muchos cacahuetes",
  "Era fácil acabar en una foliada en ese bar",
  "Nombre de un mito de la música",
  "Club de balonmano",
  "A último hora se iba a este sitio casi sin música",
  "Alguna vez resbalaste por sus escaleras y lo sabes",
  "Escultura mítica de un perro",
  "Es la gran obra de PACO",
  "Apellido de un mito de la música",
  "Ahora hay uno exterior",
  "La avenida que parece una autopista",
  "El aeropuerto que no debía existir",
  "Chico",
  "Patrimonio de la humanidad",
  "Está debajo de la torre",
  "O noso NENO",
  "El alcalde que más duró",
  "El alcalde que nadie esperaba",
  "El equipo que ganó la liga",
  "Falló un penalti el último partido de liga",
  "Su tumba está en los jardines de San  Carlos",
  "Los mejores churros",
  "Los segundos mejores churros",
  "Polígono donde está Estrella Galicia",
  "Un barrio en construcción",
  "Un barrio que quieren hacer peligroso",
  "El partido que nadie esperaba",
  "Antes se salía de fiesta por esa zona",
  "El estadio del DEPOR",
  "Culo en koruño",
  "Los mejores murales son suyos",
  "José Roberto Gama de Oliveira",
  "El mejor bar de la calle Galera",
  "El periódico que no miente",
  "Se llamaba María y nos salvó de los ingleses",
  "Galerías y cafés hay en esta calle",
  "La orquesta que toca en el palacio de la Ópera",
  "Casa en Koruño",
  "Me oyes...",
  "Chica en Koruño",
  "El barrio que tiene el parque de San Diego",
  "El barrio que atacaba a Corea ",
  "El hockey corre por su colegio",
  "Cuando te pegan en Koruño",
  "El caballito de mar que salvaron en el Aquarium",
  "El museo del vídeo del parto",
  "La calle con más viento de Coruña",
  "Perro en Koruño",
  "La primera alcaldesa",
  "Zapatería clásica",
  "Antes era la Green",
  "Basura en Koruño",
  "Hay muchas en la ciudad",
  "La calle de los bares de día",
  "La radio comunitaria de A Coruña",
  "El tribunal que nunca defrauda a Feijoo",
  "Bar de rock que fue todo un templo",
  "Twitero famoso",
  "Se hacía botellón pero ahora no se puede hablar en esa plaza",
  "El suelo de ese bar tiene muchos cacahuetes",
  "Era fácil acabar en una foliada en ese bar",
  "Nombre de un mito de la música",
  "Club de balonmano",
  "A último hora se iba a este sitio casi sin música",
  "Alguna vez resbalaste por sus escaleras y lo sabes",
  "Escultura mítica de un perro",
  "Es la gran obra de PACO",
  "Apellido de un mito de la música",
  "Ahora hay uno exterior",
  "La avenida que parece una autopista",
  "El aeropuerto que no debía existir",
  "Chico",
  "Patrimonio de la humanidad",
  "Está debajo de la torre",
  "O noso NENO",
  "El alcalde que más duró",
  "El alcalde que nadie esperaba",
  "El equipo que ganó la liga",
  "Falló un penalti el último partido de liga",
  "Su tumba está en los jardines de San  Carlos",
  "Los mejores churros",
  "Los segundos mejores churros",
  "Polígono donde está Estrella Galicia",
  "Un barrio en construcción",
  "Un barrio que quieren hacer peligroso",
  "El partido que nadie esperaba",
  "Antes se salía de fiesta por esa zona",
  "El estadio del DEPOR",
  "Culo en koruño",
  "Los mejores murales son suyos",
  "José Roberto Gama de Oliveira",
  "El mejor bar de la calle Galera",
  "El periódico que no miente",
  "Se llamaba María y nos salvó de los ingleses",
  "Galerías y cafés hay en esta calle",
  "La orquesta que toca en el palacio de la Ópera",
  "Casa en Koruño",
  "Me oyes...",
  "Chica en Koruño",
  "El barrio que tiene el parque de San Diego",
  "El barrio que atacaba a Corea ",
  "El hockey corre por su colegio",
  "Cuando te pegan en Koruño",
  "El caballito de mar que salvaron en el Aquarium",
  "El museo del vídeo del parto",
  "La calle con más viento de Coruña",
  "Perro en Koruño",
  "La primera alcaldesa",
  "Zapatería clásica",
  "Antes era la Green",
  "Basura en Koruño",
  "Hay muchas en la ciudad",
  "La calle de los bares de día",
  "La radio comunitaria de A Coruña",
  "El tribunal que nunca defrauda a Feijoo",
  "Bar de rock que fue todo un templo",
  "Twitero famoso",
  "Se hacía botellón pero ahora no se puede hablar en esa plaza",
  "El suelo de ese bar tiene muchos cacahuetes",
  "Era fácil acabar en una foliada en ese bar",
  "Nombre de un mito de la música",
  "Club de balonmano",
  "A último hora se iba a este sitio casi sin música",
  "Alguna vez resbalaste por sus escaleras y lo sabes",
  "Escultura mítica de un perro",
  "Es la gran obra de PACO",
  "Apellido de un mito de la música",
  "Ahora hay uno exterior",
  "La avenida que parece una autopista",
  "El aeropuerto que no debía existir",
  "Chico",
  "Patrimonio de la humanidad",
  "Está debajo de la torre",
  "O noso NENO",
  "El alcalde que más duró",
  "El alcalde que nadie esperaba",
  "El equipo que ganó la liga",
  "Falló un penalti el último partido de liga",
  "Su tumba está en los jardines de San  Carlos",
  "Los mejores churros",
  "Los segundos mejores churros",
  "Polígono donde está Estrella Galicia",
  "Un barrio en construcción",
  "Un barrio que quieren hacer peligroso",
  "El partido que nadie esperaba",
  "Antes se salía de fiesta por esa zona",
  "El estadio del DEPOR",
  "Culo en koruño",
  "Los mejores murales son suyos",
  "José Roberto Gama de Oliveira",
  "El mejor bar de la calle Galera",
  "El periódico que no miente",
  "Se llamaba María y nos salvó de los ingleses",
  "Galerías y cafés hay en esta calle",
  "La orquesta que toca en el palacio de la Ópera",
  "Casa en Koruño",
  "Me oyes...",
  "Chica en Koruño",
  "El barrio que tiene el parque de San Diego",
  "El barrio que atacaba a Corea ",
  "El hockey corre por su colegio",
  "Cuando te pegan en Koruño",
  "El caballito de mar que salvaron en el Aquarium",
  "El museo del vídeo del parto",
  "La calle con más viento de Coruña",
  "Perro en Koruño",
  "La primera alcaldesa",
  "Zapatería clásica",
  "Antes era la Green",
  "Basura en Koruño",
  "Hay muchas en la ciudad",
  "La calle de los bares de día",
  "La radio comunitaria de A Coruña",
  "El tribunal que nunca defrauda a Feijoo",
  "Bar de rock que fue todo un templo",
  "Twitero famoso",
  "Se hacía botellón pero ahora no se puede hablar en esa plaza",
  "El suelo de ese bar tiene muchos cacahuetes",
  "Era fácil acabar en una foliada en ese bar",
  "Nombre de un mito de la música",
  "Club de balonmano",
  "A último hora se iba a este sitio casi sin música",
  "Alguna vez resbalaste por sus escaleras y lo sabes",
  "Escultura mítica de un perro",
  "Es la gran obra de PACO",
  "Apellido de un mito de la música",
  "Ahora hay uno exterior",
  "La avenida que parece una autopista",
  "El aeropuerto que no debía existir",
  "Chico",
  "Patrimonio de la humanidad",
  "Está debajo de la torre",
  "O noso NENO",
  "El alcalde que más duró",
  "El alcalde que nadie esperaba",
  "El equipo que ganó la liga",
  "Falló un penalti el último partido de liga",
  "Su tumba está en los jardines de San  Carlos",
  "Los mejores churros",
  "Los segundos mejores churros",
  "Polígono donde está Estrella Galicia",
  "Un barrio en construcción",
  "Un barrio que quieren hacer peligroso",
  "El partido que nadie esperaba",
  "Antes se salía de fiesta por esa zona",
  "El estadio del DEPOR",
  "Culo en koruño",
  "Los mejores murales son suyos",
  "José Roberto Gama de Oliveira",
  "El mejor bar de la calle Galera",
  "El periódico que no miente",
  "Se llamaba María y nos salvó de los ingleses",
  "Galerías y cafés hay en esta calle",
  "La orquesta que toca en el palacio de la Ópera",
  "Casa en Koruño",
  "Me oyes...",
  "Chica en Koruño",
  "El barrio que tiene el parque de San Diego",
  "El barrio que atacaba a Corea ",
  "El hockey corre por su colegio",
  "Cuando te pegan en Koruño",
  "El caballito de mar que salvaron en el Aquarium",
  "El museo del vídeo del parto",
  "La calle con más viento de Coruña",
  "Perro en Koruño",
  "La primera alcaldesa",
  "Zapatería clásica",
  "Antes era la Green",
  "Basura en Koruño",
  "Hay muchas en la ciudad",
  "La calle de los bares de día",
  "La radio comunitaria de A Coruña",
  "El tribunal que nunca defrauda a Feijoo",
  "Bar de rock que fue todo un templo",
  "Twitero famoso",
  "Se hacía botellón pero ahora no se puede hablar en esa plaza",
  "El suelo de ese bar tiene muchos cacahuetes",
  "Era fácil acabar en una foliada en ese bar",
  "Nombre de un mito de la música",
  "Club de balonmano",
  "A último hora se iba a este sitio casi sin música",
  "Alguna vez resbalaste por sus escaleras y lo sabes",
  "Escultura mítica de un perro",
  "Es la gran obra de PACO",
  "Apellido de un mito de la música",
  "Ahora hay uno exterior",
  "La avenida que parece una autopista",
  "El aeropuerto que no debía existir"
];

